#! /usr/bin/env python3

if __name__ == '__main__':
    import argparse
    import os.path

    from weblib.conf import config

    parser = argparse.ArgumentParser(description="Make a web page.")
    parser.add_argument('-f', '--file', '--webfile', default="Webfile",
                        dest="webfile", metavar="file",
                        help="use %(metavar)s as the webfile")
    parser.add_argument('-t', '-targetbase', default="output",
                        dest="target_base", metavar="dir",
                        help="place target files under %(metavar)s")
    args = parser.parse_args()
    
    webfile_path = os.path.abspath(args.webfile)
    source_base = os.path.dirname(webfile_path)
    target_base = os.path.abspath(args.target_base)

    config.initialize(source_base, target_base)

    webfile = open(webfile_path, "r", encoding="utf-8")
    exec(compile(webfile.read(), webfile_path, "exec"), {}, {})
